<?xml version="1.0"?>
<package format="3">
  <name>direct_pose</name>
  <version>0.0.0</version>
  <description>Move robot to a specific pose</description>
  <maintainer email="your@email.com">your_name</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_python</buildtool_depend>
  <exec_depend>rclpy</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>

